version: "3"
services:
  app:
    build: .
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: inventario
      MYSQL_USER: inventario_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
